//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desafio_Intelectah.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exame
    {
        public int id { get; set; }
        public string nome { get; set; }
        public string observacoes { get; set; }
        public int tipo_exame { get; set; }
    
        public virtual Tipo_de_exame Tipo_de_exame { get; set; }
    }
}
