//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desafio_Intelectah.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente
    {
        public int id { get; set; }
        public string nome { get; set; }
        public string cpf { get; set; }
        public System.DateTime data_nascimento { get; set; }
        public string sexo { get; set; }
        public string telefone { get; set; }
        public string email { get; set; }
    }
}
